spring.application.name=serviceA1
server.port=9091

management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#Resilance-4j  properties
resilience4j.circuitbreaker.instances.serviceA.register-health-indicator=true
resilience4j.circuitbreaker.instances.serviceA.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instances.serviceA.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.serviceA.sliding-window-size=5
resilience4j.circuitbreaker.instances.serviceA.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.serviceA.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.serviceA.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.serviceA.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.serviceA.sliding-window-type=COUNT_BASED

#Retry properties
resilience4j.retry.instances.serviceA.max-attempts=4
resilience4j.retry.instances.serviceA.wait-duration=5s


# RateLimiter configuration
resilience4j.ratelimiter.instances.serviceA.limitForPeriod=5
resilience4j.ratelimiter.instances.serviceA.limitRefreshPeriod=10s
resilience4j.ratelimiter.instances.serviceA.timeoutDuration=2s
resilience4j.ratelimiter.instances.serviceA.registerHealthIndicator=true
resilience4j.ratelimiter.instances.serviceA.eventConsumerBufferSize=100