spring.application.name=API-GATEWAY1
server.port=8085

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.client.healthcheck.enabled=true

## Employee Route
#spring.cloud.gateway.routes[0].id=employee-service
#spring.cloud.gateway.routes[0].uri=lb://EMPLOYEE-SERVICE
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/employee/**
#
## Department Route
#spring.cloud.gateway.routes[1].id=department-service
#spring.cloud.gateway.routes[1].uri=lb://DEPARTMENT-SERVICE
#spring.cloud.gateway.routes[1].predicates[0]=Path=/api/department/**

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Enable Locator
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true