spring.application.name=CONFIG-SERVER	
server.port=9999
spring.cloud.config.server.git.uri=https://github.com/nandini2001-np/config-server-repo.git
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=main